name: "tests"
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  e2e-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install playwright
        run: npx playwright install --with-deps
      - name: Run tests
        run: npm test
